# Sonar Rock vs Mine Classification

## Import Libraries

In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## Load Dataset

In [28]:
sonar_data = pd.read_csv('../data/sonar_data.csv', header=None)
sonar_data.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

## Exploratory Data Analysis

In [29]:
sonar_data.shape

(208, 61)

In [30]:
sonar_data.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [31]:
sonar_data[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [32]:
sonar_data.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

## Data Preparation

In [33]:
X = sonar_data.drop(columns=60, axis=1)
y = sonar_data[60]

In [34]:
print(X,y)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

         57      58      59
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
203  0.0115  0.0193  0.0157
204  0.0032  0.0062  0.0067
205  0.0138  0.0077  0.0031
206  0.0079  0.0036  0.0048
207  0.0036  0.0061  0.0115

[208 rows x 60 columns] 0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

## Train-Test Split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [36]:
print(X.shape, X_train.shape, X_test.shape)

(208, 60) (166, 60) (42, 60)

In [37]:
print(X_train, y_train)

         0       1       2       3       4       5       6       7       8   \
97   0.0491  0.0279  0.0592  0.1270  0.1772  0.1908  0.2217  0.0768  0.1246
132  0.0968  0.0821  0.0629  0.0608  0.0617  0.1207  0.0944  0.4223  0.5744
201  0.0335  0.0258  0.0398  0.0570  0.0529  0.1091  0.1709  0.1684  0.1865
54   0.0132  0.0080  0.0188  0.0141  0.0436  0.0668  0.0609  0.0131  0.0899
105  0.0116  0.0179  0.0449  0.1096  0.1913  0.0924  0.0761  0.1092  0.0757
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
41   0.0093  0.0185  0.0056  0.0064  0.0260  0.0458  0.0470  0.0057  0.0425
116  0.0094  0.0333  0.0306  0.0376  0.1296  0.1795  0.1909  0.1692  0.1870
87   0.0856  0.0454  0.0382  0.0203  0.0385  0.0534  0.2140  0.3110  0.2837
78   0.0231  0.0351  0.0030  0.0304  0.0339  0.0860  0.1738  0.1351  0.1063
69   0.0216  0.0215  0.0273  0.0139  0.0357  0.0785  0.0906  0.0908  0.1151

         9   ...      50      51      52      53      54      55      56  \
97   0.2028  ...  0.0268  0.0081  0.0129  0.0161  0.0063  0.0119  0.0194
132  0.5025  ...  0.0206  0.0073  0.0081  0.0303  0.0190  0.0212  0.0126
201  0.2660  ...  0.0130  0.0120  0.0039  0.0053  0.0062  0.0046  0.0045
54   0.0922  ...  0.0136  0.0044  0.0028  0.0021  0.0022  0.0048  0.0138
105  0.1006  ...  0.0031  0.0163  0.0099  0.0084  0.0270  0.0277  0.0097
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
41   0.0640  ...  0.0022  0.0069  0.0064  0.0129  0.0114  0.0054  0.0089
116  0.1725  ...  0.0216  0.0153  0.0112  0.0241  0.0164  0.0055  0.0078
87   0.2751  ...  0.0128  0.0172  0.0138  0.0079  0.0037  0.0051  0.0258
78   0.0347  ...  0.0154  0.0106  0.0097  0.0022  0.0052  0.0072  0.0056
69   0.0973  ...  0.0082  0.0140  0.0044  0.0052  0.0073  0.0021  0.0047

         57      58      59
97   0.0140  0.0332  0.0439
132  0.0201  0.0210  0.0041
201  0.0022  0.0005  0.0031
54   0.0140  0.0028  0.0064
105  0.0054  0.0148  0.0092
..      ...     ...     ...
41   0.0050  0.0058  0.0025
116  0.0055  0.0091  0.0067
87   0.0102  0.0037  0.0037
78   0.0038  0.0043  0.0030
69   0.0024  0.0009  0.0017

[166 rows x 60 columns] 97     M
132    M
201    M
54     R
105    M
      ..
41     R
116    M
87     R
78     R
69     R
Name: 60, Length: 166, dtype: object

In [38]:
print(X_test, y_test)

         0       1       2       3       4       5       6       7       8   \
96   0.0181  0.0146  0.0026  0.0141  0.0421  0.0473  0.0361  0.0741  0.1398
22   0.0099  0.0484  0.0299  0.0297  0.0652  0.1077  0.2363  0.2385  0.0075
6    0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083
148  0.0712  0.0901  0.1276  0.1497  0.1284  0.1165  0.1285  0.1684  0.1830
194  0.0392  0.0108  0.0267  0.0257  0.0410  0.0491  0.1053  0.1690  0.2105
184  0.0269  0.0383  0.0505  0.0707  0.1313  0.2103  0.2263  0.2524  0.3595
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
77   0.0336  0.0294  0.0476  0.0539  0.0794  0.0804  0.1136  0.1228  0.1235
98   0.1313  0.2339  0.3059  0.4264  0.4010  0.1791  0.1853  0.0055  0.1929
99   0.0201  0.0423  0.0554  0.0783  0.0620  0.0871  0.1201  0.2707  0.1206
72   0.0208  0.0186  0.0131  0.0211  0.0610  0.0613  0.0612  0.0506  0.0989
179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618
32   0.0195  0.0213  0.0058  0.0190  0.0319  0.0571  0.1004  0.0668  0.0691
61   0.0135  0.0045  0.0051  0.0289  0.0561  0.0929  0.1031  0.0883  0.1596
27   0.0177  0.0300  0.0288  0.0394  0.0630  0.0526  0.0688  0.0633  0.0624
40   0.0068  0.0232  0.0513  0.0444  0.0249  0.0637  0.0422  0.1130  0.1911
149  0.0207  0.0535  0.0334  0.0818  0.0740  0.0324  0.0918  0.1070  0.1553
171  0.0179  0.0136  0.0408  0.0633  0.0596  0.0808  0.2090  0.3465  0.5276
33   0.0442  0.0477  0.0049  0.0581  0.0278  0.0678  0.1664  0.1490  0.0974
118  0.0363  0.0478  0.0298  0.0210  0.1409  0.1916  0.1349  0.1613  0.1703
196  0.0050  0.0017  0.0270  0.0450  0.0958  0.0830  0.0879  0.1220  0.1977
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
168  0.0015  0.0186  0.0289  0.0195  0.0515  0.0817  0.1005  0.0124  0.1168
34   0.0311  0.0491  0.0692  0.0831  0.0079  0.0200  0.0981  0.1016  0.2025
36   0.0094  0.0166  0.0398  0.0359  0.0681  0.0706  0.1020  0.0893  0.0381
64   0.0071  0.0103  0.0135  0.0494  0.0253  0.0806  0.0701  0.0738  0.0117
46   0.0308  0.0339  0.0202  0.0889  0.1570  0.1750  0.0920  0.1353  0.1593
111  0.0530  0.0885  0.1997  0.2604  0.3225  0.2247  0.0617  0.2287  0.0950
199  0.0116  0.0744  0.0367  0.0225  0.0076  0.0545  0.1110  0.1069  0.1708
11   0.0123  0.0309  0.0169  0.0313  0.0358  0.0102  0.0182  0.0579  0.1122
47   0.0373  0.0281  0.0232  0.0225  0.0179  0.0733  0.0841  0.1031  0.0993
126  0.0715  0.0849  0.0587  0.0218  0.0862  0.1801  0.1916  0.1896  0.2960
43   0.0093  0.0269  0.0217  0.0339  0.0305  0.1172  0.1450  0.0638  0.0740
117  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
183  0.0096  0.0404  0.0682  0.0688  0.0887  0.0932  0.0955  0.2140  0.2546
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843
157  0.0201  0.0178  0.0274  0.0232  0.0724  0.0833  0.1232  0.1298  0.2085
120  0.0346  0.0509  0.0079  0.0243  0.0432  0.0735  0.0938  0.1134  0.1228
134  0.1083  0.1070  0.0257  0.0837  0.0748  0.1125  0.3322  0.4590  0.5526
189  0.0158  0.0239  0.0150  0.0494  0.0988  0.1425  0.1463  0.1219  0.1697
71   0.0036  0.0078  0.0092  0.0387  0.0530  0.1197  0.1243  0.1026  0.1239

         9   ...      50      51      52      53      54      55      56  \
96   0.1045  ...  0.0076  0.0223  0.0255  0.0145  0.0233  0.0041  0.0018
22   0.1882  ...  0.0396  0.0173  0.0149  0.0115  0.0202  0.0139  0.0029
6    0.3513  ...  0.0195  0.0201  0.0248  0.0131  0.0070  0.0138  0.0092
148  0.2127  ...  0.0154  0.0154  0.0156  0.0054  0.0030  0.0048  0.0087
194  0.2471  ...  0.0089  0.0083  0.0080  0.0026  0.0079  0.0042  0.0071
184  0.5915  ...  0.0346  0.0167  0.0199  0.0145  0.0081  0.0045  0.0043
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
77   0.0842  ...  0.0033  0.0150  0.0111  0.0032  0.0035  0.0169  0.0137
98   0.2231  ...  0.0156  0.0362  0.0210  0.0154  0.0180  0.0013  0.0106
99   0.0279  ...  0.0081  0.0191  0.0182  0.0160  0.0290  0.0090  0.0242
72   0.1093  ...  0.0140  0.0074  0.0063  0.0081  0.0087  0.0044  0.0028
179  0.2558  ...  0.0118  0.0146  0.0040  0.0114  0.0032  0.0062  0.0101
32   0.0242  ...  0.0261  0.0157  0.0074  0.0271  0.0203  0.0089  0.0095
61   0.1908  ...  0.0025  0.0037  0.0084  0.0102  0.0096  0.0024  0.0037
27   0.0613  ...  0.0168  0.0102  0.0122  0.0044  0.0075  0.0124  0.0099
40   0.2475  ...  0.0199  0.0173  0.0163  0.0055  0.0045  0.0068  0.0041
149  0.1234  ...  0.0171  0.0033  0.0050  0.0190  0.0103  0.0121  0.0042
171  0.5965  ...  0.0086  0.0123  0.0060  0.0187  0.0111  0.0126  0.0081
33   0.1268  ...  0.0210  0.0204  0.0216  0.0135  0.0055  0.0073  0.0080
118  0.1444  ...  0.0250  0.0115  0.0190  0.0055  0.0096  0.0050  0.0066
196  0.2282  ...  0.0281  0.0165  0.0056  0.0010  0.0027  0.0062  0.0024
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
168  0.1476  ...  0.0045  0.0108  0.0075  0.0089  0.0036  0.0029  0.0013
34   0.0767  ...  0.0089  0.0087  0.0032  0.0130  0.0188  0.0101  0.0229
36   0.1328  ...  0.0134  0.0141  0.0191  0.0145  0.0065  0.0129  0.0217
64   0.0898  ...  0.0252  0.0043  0.0048  0.0076  0.0124  0.0105  0.0054
46   0.2795  ...  0.0070  0.0167  0.0127  0.0138  0.0090  0.0051  0.0029
111  0.0740  ...  0.0299  0.0244  0.0199  0.0257  0.0082  0.0151  0.0171
199  0.2271  ...  0.0202  0.0141  0.0103  0.0100  0.0034  0.0026  0.0037
11   0.0835  ...  0.0188  0.0133  0.0265  0.0224  0.0074  0.0118  0.0026
47   0.0802  ...  0.0066  0.0008  0.0045  0.0024  0.0006  0.0073  0.0096
126  0.4186  ...  0.0216  0.0153  0.0121  0.0096  0.0196  0.0042  0.0066
43   0.1360  ...  0.0309  0.0212  0.0091  0.0056  0.0086  0.0092  0.0070
117  0.2227  ...  0.0185  0.0098  0.0178  0.0077  0.0074  0.0095  0.0055
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
183  0.2952  ...  0.0310  0.0237  0.0078  0.0144  0.0170  0.0012  0.0109
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040
157  0.2720  ...  0.0253  0.0131  0.0049  0.0104  0.0102  0.0092  0.0083
120  0.1508  ...  0.0146  0.0040  0.0122  0.0107  0.0112  0.0102  0.0052
134  0.5966  ...  0.0172  0.0180  0.0110  0.0234  0.0276  0.0032  0.0084
189  0.1923  ...  0.0223  0.0121  0.0108  0.0057  0.0028  0.0079  0.0034
71   0.0888  ...  0.0079  0.0119  0.0055  0.0035  0.0036  0.0004  0.0018

         57      58      59
96   0.0048  0.0089  0.0085
22   0.0160  0.0106  0.0134
6    0.0143  0.0036  0.0103
148  0.0101  0.0095  0.0068
194  0.0044  0.0022  0.0014
184  0.0027  0.0055  0.0057
203  0.0115  0.0193  0.0157
77   0.0015  0.0069  0.0051
98   0.0127  0.0178  0.0231
99   0.0224  0.0190  0.0096
72   0.0019  0.0049  0.0023
179  0.0068  0.0053  0.0087
32   0.0095  0.0021  0.0053
61   0.0028  0.0030  0.0030
27   0.0057  0.0032  0.0019
40   0.0052  0.0194  0.0105
149  0.0090  0.0070  0.0099
171  0.0155  0.0160  0.0085
33   0.0105  0.0059  0.0105
118  0.0114  0.0073  0.0033
196  0.0063  0.0017  0.0028
4    0.0048  0.0107  0.0094
168  0.0010  0.0032  0.0047
34   0.0182  0.0046  0.0038
36   0.0087  0.0077  0.0122
64   0.0032  0.0073  0.0063
46   0.0122  0.0056  0.0020
111  0.0146  0.0134  0.0056
199  0.0044  0.0057  0.0035
11   0.0092  0.0009  0.0044
47   0.0054  0.0085  0.0060
126  0.0099  0.0083  0.0124
43   0.0116  0.0060  0.0110
117  0.0045  0.0063  0.0039
2    0.0164  0.0095  0.0078
183  0.0036  0.0043  0.0018
207  0.0036  0.0061  0.0115
157  0.0020  0.0048  0.0036
120  0.0024  0.0079  0.0031
134  0.0122  0.0082  0.0143
189  0.0046  0.0022  0.0021
71   0.0049  0.0024  0.0016

[42 rows x 60 columns] 96     R
22     R
6      R
148    M
194    M
184    M
203    M
77     R
98     M
99     M
72     R
179    M
32     R
61     R
27     R
40     R
149    M
171    M
33     R
118    M
196    M
4      R
168    M
34     R
36     R
64     R
46     R
111    M
199    M
11     R
47     R
126    M
43     R
117    M
2      R
183    M
207    M
157    M
120    M
134    M
189    M
71     R
Name: 60, dtype: object

## Model Training

In [39]:
model = LogisticRegression()

In [40]:
model.fit(X_train, y_train)

/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

LogisticRegression()

## Model Evaluation

In [41]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

print('Accuracy data on training data:', training_data_accuracy)

Accuracy data on training data: 0.8373493975903614

/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [42]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)

print('Accuracy data on testing data:', test_data_accuracy)

Accuracy data on testing data: 0.8571428571428571

/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/zulfaarsyandhiazra/Library/Python/3.9/lib/python/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

## Prediction

In [43]:
input_data = (0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,0.4152,0.3952,0.4256,0.4135,0.4528,0.5326,0.7306,0.6193,0.2032,0.4636,0.4148,0.4292,0.5730,0.5399,0.3161,0.2285,0.6995,1.0000,0.7262,0.4724,0.5103,0.5459,0.2881,0.0981,0.1951,0.4181,0.4604,0.3217,0.2828,0.2430,0.1979,0.2444,0.1847,0.0841,0.0692,0.0528,0.0357,0.0085,0.0230,0.0046,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094)
input_data_as_array = np.asarray(input_data)

input_data_reshaped = input_data_as_array.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
    print("The object is Rock")
else:
    print("The object is Mine")

['M']
The object is Mine